# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SiBUbmG2Ijxvt6QVKN6hYGrwTJpFbqzR
"""

import gradio as gr

def to_uppercase(text):
  return text.upper()

demo = gr.Interface(
    fn=to_uppercase,
    inputs="text",
    outputs="text",
    title="Text to Uppercase",
    description="Enter some text and see it converted to uppercase."
)
if __name__ == "__main__":
  demo.launch(
    share=True
)